# version: "3"

# services:
#   mysql:
#     platform: linux/amd64
#     image: mysql:8.0
#     environment:
#       MYSQL_DATABASE: reimagined_spork
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#       MYSQL_ROOT_PASSWORD: password
#     restart: always
#     command: --explicit_defaults_for_timestamp=1
#     networks:
#       - net_app
#     ports:
#       - "3306:3306"
#     expose:
#       - "3306"
#     volumes:
#       - reimagined-spork:/var/lib/mysql

# networks:
#   net_app:
#     driver: bridge

# volumes:
#   reimagined-spork:

version: "3"

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: reimagined_spork
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - net_app
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - reimagined-spork:/var/lib/mysql

networks:
  net_app:
    driver: bridge

volumes:
  reimagined-spork:
